name: counter_app
description: A new Flutter project

environment:
  sdk: ">=3.4.0 <4.0.0"  # Specify the Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1  # Add google_fonts dependency

dev_dependencies:
  flutter_launcher_icons: ^0.9.2  # Add flutter_launcher_icons dependency

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icon/app_icon.png  # Make sure the icon is included in assets
  fonts:
    - family: Anta
      fonts:
        - asset: assets/fonts/Anta-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  # Path to your app icon

version: 1.0.0+1